# Generated by Django 3.0.6 on 2020-06-02 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='userworkbench',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userworkbench',
            old_name='workbench_id',
            new_name='workbench',
        ),
        migrations.RenameField(
            model_name='workbench',
            old_name='workshop_id',
            new_name='workshop',
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1024)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.Card')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.Step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='workbench',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Workbench'),
        ),
    ]
