# Generated by Django 3.0.6 on 2020-06-11 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_workbench'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbench',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
