# Generated by Django 3.0.6 on 2020-06-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_workbench_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userworkbench',
            constraint=models.UniqueConstraint(fields=('user', 'workbench'), name='unique_assign'),
        ),
    ]
