# Generated by Django 3.0.6 on 2020-06-11 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_userworkbench_unique_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkbench',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
