# Generated by Django 3.0.6 on 2020-06-16 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_userworkbench_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='sticky', max_length=20)),
                ('content', models.CharField(max_length=1024)),
                ('matrix', models.CharField(max_length=1024, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.Card')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.Step')),
            ],
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workbench',
            name='workshop',
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
