# Generated by Django 3.0.6 on 2020-06-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_userworkbench_created_at'),
        ('workshop', '0007_userworkbench_unique_assign'),
    ]

    operations = [
    ]
