# Generated by Django 3.0.6 on 2020-06-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_card_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sup_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
