# Generated by Django 3.0.6 on 2020-06-18 11:36

from django.db import migrations
import workshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_remove_user_wechat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='matrix',
        ),
        migrations.AddField(
            model_name='element',
            name='meta',
            field=workshop.models.JSONField(max_length=1024, null=True),
        ),
    ]
