# Generated by Django 3.0.6 on 2020-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_auto_20200622_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
