# Generated by Django 3.0.6 on 2020-06-28 14:08

from django.db import migrations
import workshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0018_auto_20200623_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=workshop.models.JSONField(),
        ),
    ]
