# Generated by Django 3.0.6 on 2020-06-29 10:06

from django.db import migrations
import workshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0019_update_card_description_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='content',
            field=workshop.models.JSONField(),
        ),
    ]
