# Generated by Django 3.0.6 on 2020-07-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_update_element_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='ref_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.Element'),
        ),
    ]
