name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 54.223.213.169
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd LDD-OnelineWorkshop-Backend
          git pull
          sh deploy/build_image.sh
          sudo docker-compose -f deploy/docker-compose.yml down
          sudo docker-compose -f deploy/docker-compose.yml up -d

